version: '3.8'

services:

  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'cifras'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
