name: Build and publish

on:
  push:
    tags:
      - "*" # Running this workflow for any tag

jobs:
  build-and-publish-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Build and publish Docker image tagged according to a git-tag
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: cifras-backend # Provide only Docker image name
          extract-git-tag: true # Provide flag to extract Docker image tag from git reference